// <auto-generated />
using System;
using CyprusTaxCalculator.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CyprusTaxCalculator.DAL.Migrations
{
    [DbContext(typeof(TaxDbContext))]
    [Migration("20250817111858_AddUserCalculationHistory")]
    partial class AddUserCalculationHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CyprusTaxCalculator.DAL.Entities.DeductionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeductionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LimitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LimitValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DeductionRules");
                });

            modelBuilder.Entity("CyprusTaxCalculator.DAL.Entities.TaxBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MaxIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TaxBrackets");
                });

            modelBuilder.Entity("CyprusTaxCalculator.DAL.Entities.UserCalculationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LifeInsurancePremiums")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxSavings")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxableIncome")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserCalculationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
