name: Dependency-Check
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  dep-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "CyprusTaxCalculator"
          path: "."
          format: "HTML,JSON"
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: |
            dependency-check-report.html
            dependency-check-report.json