name: .NET CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore CyprusTaxCalculator.sln

      - name: Build (warnings fail CI)
        run: dotnet build CyprusTaxCalculator.sln --configuration Release --no-restore -warnaserror

      - name: Test
        run: dotnet test CyprusTaxCalculator.sln --configuration Release --no-build --verbosity normal